### ISSUE TITLE
after installation

### ISSUE THREAD

**Issue by sechanbask** [CyrilWaechter/pythoncvc.net#1]
Hi,

I'm trying revitpython shell and your pythoncvc.net. 

I have intall it, il see it into revit, but I can't  rename the view : 

Traceback (most recent call last):
  File "<string>", line 26, in <module>
AttributeError: 'NoneType' object has no attribute 'AsElementId'

rotation axe X works, but is it possible to rotate 45° by 45° ?

How to add http://pythoncvc.net/?p=116 ?

**Comment by CyrilWaechter** [comment]
Hi,

I'm not able to reproduce you error message. I tried to select nothing, it just do nothing, I tried to select an invalid object, same. And if I select views it works. Which version of Revit and RPS do you use ? Can you describe actions you did to get you error message ? The selected object seems invalid

To rotate 45° by 45°, you just need to change «pi/2» to «pi/4» line 27.

To add an other function check the tutorial on how to use Revit Python Shell : [http://pythoncvc.net/?p=44](http://pythoncvc.net/?p=44)

**Comment by sechanbask** [comment]
Hi, 

Thnak you for your fast answer. 

I'm using REVIT 2015 and 2015.04.29_Setup_RevitPythonShell_2015. I don't
understand the aim of  "renommer la vue". Can you explain to me ? 

To rotate 45° by 45°, you just need to change «pi/2» to «pi/4» line 27.
-> Ok, but where is the file I have to change ? 

Are you french ? 

Le 02.10.2016 13:53, Nahouhak a écrit :

> Hi, 
> 
> I'm not able to reproduce you error message. I tried to select nothing, it just do nothing, I tried to select an invalid object, same. And if I select views it works. Which version of Revit and RPS do you use ? Can you describe actions you did to get you error message ? The selected object seems invalid 
> 
> To rotate 45° by 45°, you just need to change «pi/2» to «pi/4» line 27. 
> 
> To add an other function check the tutorial on how to use Revit Python Shell : http://pythoncvc.net/?p=44 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

## Links:

[1]
https://github.com/Nahouhak/pythoncvc.net/issues/1#issuecomment-250967624
[2]

**Comment by CyrilWaechter** [comment]
Hi,
«rennomer la vue» means «rename the view». It is a tool to batch rename views according to a specific rule. For example if at the beginning of the project you create multiple views for each level (scope box, HVAC, plumbing, electricity etc…) Revit natively give it a name like E0, E0 (1), E0 (2) etc… It's quiet painful to rename it manually.

The file is on github right here : [https://github.com/Nahouhak/pythoncvc.net/blob/master/RevitPyCVC/Outils/renommer_vues.py](https://github.com/Nahouhak/pythoncvc.net/blob/master/RevitPyCVC/Outils/renommer_vues.py)
If you don't know how to use github you should try to find a tutorial like this : [https://www.udemy.com/short-and-sweet-get-started-with-git-and-github-right-now/](https://www.udemy.com/short-and-sweet-get-started-with-git-and-github-right-now/)

Yes my native language is french. I should probably translate comments and file names for a more international readability.
