### ISSUE TITLE
developpement

### ISSUE THREAD

**Issue by sechanbask** [CyrilWaechter/pythoncvc.net#2]
Bonjour,

Est-ce que vous faites du développement à la demande ?

Si oui combien pour un script pour import des polylignes depuis dwg pour en faire des tuyaux sous revit ?

**Comment by CyrilWaechter** [comment]
Bonjour,
Cela pourrait-être intéressant mais j'ai assez peu de disponibilités en ce moment. C'est urgent ? Le mieux est de me contacter par [mail](mailto:cyril@biminsight.ch) pour ce type de demande.

**Comment by sechanbask** [comment]
Pas vraiment d'urgence, ça serait pour améliorer mon quotidien, faire des coupes à profondeur et hauteur fixe, faire de vérification de débit par rapport à des valeurs tabulées...

Je vais rencontrer un développeur local dans la semaine 



Le 13 février 2017 16:15:45 GMT+01:00, Nahouhak <notifications@github.com> a écrit :
>Bonjour,
>Cela pourrait-être intéressant mais j'ai assez peu de disponibilités en
>ce moment. C'est urgent ? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nahouhak/pythoncvc.net/issues/2#issuecomment-279420338

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sechanbask** [comment]
Si ça marche pas avec lui, je vous recontacterais 

Le 13 février 2017 16:15:45 GMT+01:00, Nahouhak <notifications@github.com> a écrit :
>Bonjour,
>Cela pourrait-être intéressant mais j'ai assez peu de disponibilités en
>ce moment. C'est urgent ? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nahouhak/pythoncvc.net/issues/2#issuecomment-279420338

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
